//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutionHouse1
    {
        public string Frequency { get; set; }
        public Nullable<System.DateTime> AuctionSeedDate { get; set; }
        public string Email1 { get; set; }
        public int STAGE { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> EmployeeID1 { get; set; }
        public Nullable<int> EmployeeID12 { get; set; }
        public Nullable<int> EmployeeID123 { get; set; }
        public Nullable<int> EmployeeID124 { get; set; }
        public Nullable<System.TimeSpan> SaleTime { get; set; }
    }
}
